### ISSUE TITLE
How to compile _2016/eola?

### ISSUE THREAD

**Issue by pyiso80** [3b1b/videos#13]
I'd like to run scenes from EoLA. I understood that EoLA was a bit too old to run with manimgl 1.2.0. So I checked out this particular commit:

commit 73ff0af63de1cd382e1c8552aa1c97d07e4e8744
Author: Grant Sanderson <grantsanderson7@gmail.com>
Date:   Sat Sep 24 22:46:17 2016 -0700
End of EoLA

to get to the state when EoLA was completed. 

But it seems to me that codes under _2016/eola have been updated for newer versions of manim even though they are not fully updated yet so that they can be run without changing anything. Therefore they can not be run with the above commit of manim either.

Would it be possible to get the version of EoLA source code as it exactly was when the above particular commit was made?

**Comment by 3b1b** [comment]
At that point, all the video code was in the manim repo, so you'd want to look for the version that existed there.
