### ISSUE TITLE
Number recognition issue

### ISSUE THREAD

**Issue by oscarguinane** [3b1b/videos#14]
Funny issue, the example in chapter 1, _"But what is a Neural Network?"_ [here](https://www.3blue1brown.com/lessons/neural-networks) powered by [this](https://github.com/3b1b/videos/blob/master/_2017/nn/part1.py) file recognizes short-tailed 5's as 3's.

<img width="770" alt="Screen Shot 2021-12-31 at 15 19 GMT" src="https://user-images.githubusercontent.com/4477702/147830281-2a24ae94-bd27-46c8-9be7-2b7a8c393889.png">

**Comment by 3b1b** [comment]
How interesting!  I suppose it's a quirk of how this particular network was trained, and a good lesson in why old-fashioned multilayered perceptrons have a lot of room for improvement :)
