### ISSUE TITLE
Wordle Solver Errors (ffmpeg & manim_imports_ext)

### ISSUE THREAD

**Issue by ZoomGC** [3b1b/videos#16]
So, I tried running the script (OS: Kali Linux) and ran into some errors, I fixed those by moving the packages to the correct files, but now I get this:
```
┌──(alastor㉿localhost)-[~/videos/_2022]
└─$ python3.9 ./wordle.py
/home/alastor/.local/lib/python3.9/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "/home/alastor/videos/_2022/./wordle.py", line 1, in <module>
    from manim_imports_ext import *
  File "/usr/lib/python3.9/dist-packages/manim_imports_ext.py", line 3, in <module>
    from custom.backdrops import *
  File "/usr/lib/python3.9/dist-packages/custom/backdrops.py", line 10, in <module>
    from manimlib.mobject.svg.tex_mobject import TexText
ImportError: cannot import name 'TexText' from 'manimlib.mobject.svg.tex_mobject' (/home/alastor/.local/lib/python3.9/site-packages/manimlib/mobject/svg/tex_mobject.py)
```
The reason for this (to me) is unknown, I have tried some basic research on it but to no avail

I even ran
```
pip3 install ffmpeg
```
in which ffmpeg 1.4 was installed but it still did not help

**Comment by umaruta4** [comment]
for the TexText problem it's because I tried doing 

pip install manimlib

i fixed it by doing

pip install manimgl



my new problem right now is :

DATA_DIR = os.path.join(get_directories()["data"], "wordle")
KeyError: 'data


after checking what returns from get_directories(), it seems that there's no key for 'data'. I don't really know what's inside this 'data' so I can't fix it

**Comment by Futuremappermydud** [comment]
edit custom_config.yml

**Comment by ZoomGC** [comment]
> for the TexText problem it's because I tried doing
> 
> pip install manimlib
> 
> i fixed it by doing
> 
> pip install manimgl
> 
> my new problem right now is :
> 
> DATA_DIR = os.path.join(get_directories()["data"], "wordle") KeyError: 'data
> 
> after checking what returns from get_directories(), it seems that there's no key for 'data'. I don't really know what's inside this 'data' so I can't fix it

This fixed my issue ^^. For anyone else having issues with get_coord go to (https://github.com/3b1b/manim/issues/1732) as 3b1b used a different version of manim
