### ISSUE TITLE
keyError : 'data' from wordle.py

### ISSUE THREAD

**Issue by umaruta4** [3b1b/videos#18]
DATA_DIR = os.path.join(get_directories()["data"], "wordle")
KeyError: 'data'

after checking what get_directories() returns, I can't seem to find any key named data

so what is inside this 'data' ?

**Comment by umaruta4** [comment]
just so anyone wondering how to get the get_directories() function is by :

from manimlib.utils.directories import get_directories

**Comment by arun279** [comment]
I'm having the same issue. can't seem to find this data directory.

**Comment by TonyCrane** [comment]
It is a setting in the yml file

**Comment by Nata-4681** [comment]
Can anyone help with this?
______________________________________________________________

C:\Users\Name\AppData\Local\Programs\Python\Python38\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "C:/Users/Name/Desktop/videos-master/videos-master/_2022/wordle.py", line 10, in <module>
    DATA_DIR = os.path.join(get_directories()["data"], "wordle")
KeyError: 'data
![Screenshot 2022-02-07 213005](https://user-images.githubusercontent.com/45345266/152906580-44de56e9-a354-44f7-aef4-171f2b76c7ba.png)
'

**Comment by Futuremappermydud** [comment]
Set the path in custom_config.yml and drag it into the folder

**Comment by Nata-4681** [comment]
Set the path to the "wordle_data" folder in directories "temporary_storage" ?
![Screenshot 2022-02-07 221505](https://user-images.githubusercontent.com/45345266/152911402-a1dc6a53-f954-4996-86b3-34fec72fb6d7.png)

**Comment by Futuremappermydud** [comment]
directories:
  mirror_module_path: True
  output: "/Users/grant/Dropbox/3Blue1Brown/videos"
  raster_images: "/Users/grant/Dropbox/3Blue1Brown/images/raster"
  vector_images: "/Users/grant/Dropbox/3Blue1Brown/images/vector"
  pi_creature_images: "/Users/grant/Dropbox/3Blue1Brown/images/pi_creature/svg"
  sounds: "/Users/grant/Dropbox/3Blue1Brown/sounds"
  data: "/data"
  temporary_storage: "/Users/grant/Dropbox/3Blue1Brown/manim_cache"
universal_import_line: "from manim_imports_ext import *"

**Comment by Futuremappermydud** [comment]
![image](https://user-images.githubusercontent.com/54294576/152911871-547cc3fa-2ae7-43d4-8943-e5bd82113f5f.png)

**Comment by Nata-4681** [comment]
Thanks, seems to have solved the issue. Only problem is manim imports remain unresolved and now pattern_matrix.npy cannot be retrieved.
![Screenshot 2022-02-07 222710](https://user-images.githubusercontent.com/45345266/152912652-db0b08aa-92ce-4463-92df-ebeeec9cd9b4.png)
![Screenshot 2022-02-07 222944](https://user-images.githubusercontent.com/45345266/152912670-a26ddf3a-f3bb-4625-94bf-310595b192e9.png)

**Comment by sriharshamadala** [comment]
@Nata-4681, if you edit the custom_config.yml to change the 'data' field like "./data" make sure to create a local dir data and a subdir wordle inside it.

**Comment by Frontgecko** [comment]
> @Nata-4681, if you edit the custom_config.yml to change the 'data' field like "./data" make sure to create a local dir data and a subdir wordle inside it.

I followed the comments in this thread and have the same issue.  Created the local data directory with the subdirectory of wordle.  When running the python script, it spits out the NPY file but I see no other graphics.  When trying to run the python script via command line, I have the same error: 
DATA_DIR = os.path.join(get_directories()["data"], "wordle")
KeyError: 'data'
<img width="629" alt="image" src="https://user-images.githubusercontent.com/36797168/153010123-8a290486-2906-4761-a323-5c29a14ae0bf.png">

**Comment by Frontgecko** [comment]
> > @Nata-4681, if you edit the custom_config.yml to change the 'data' field like "./data" make sure to create a local dir data and a subdir wordle inside it.
> 
> I followed the comments in this thread and have the same issue. Created the local data directory with the subdirectory of wordle. When running the python script, it spits out the NPY file but I see no other graphics. When trying to run the python script via command line, I have the same error: DATA_DIR = os.path.join(get_directories()["data"], "wordle") KeyError: 'data' <img alt="image" width="629" src="https://user-images.githubusercontent.com/36797168/153010123-8a290486-2906-4761-a323-5c29a14ae0bf.png">

Nevermind I figured it out, was attempting to run the wordle.py from the wrong subdirectory.  After running it out from manim folder, it ran perfectly.  Thank you.

**Comment by i-am-unknown-81514525** [comment]
What is the data of custom_config.yml

**Comment by Nata-4681** [comment]
I realized I am actually missing the file itself.. and I cannot find it in the GitHub folder either? Where does one find pattern_matrix.npy?

![Screenshot 2022-02-08 220116](https://user-images.githubusercontent.com/45345266/153113867-e24160b6-4244-461d-8cf2-ce4dbe482369.png)

**Comment by cornflakesdev** [comment]
> I realized I am actually missing the file itself.. and I cannot find it in the GitHub folder either? Where does one find pattern_matrix.npy? Forgive me if I am missing it but for some reason it is not there?
> 
> ![Screenshot 2022-02-08 220116](https://user-images.githubusercontent.com/45345266/153113867-e24160b6-4244-461d-8cf2-ce4dbe482369.png)

It is generated, along with the other files not found in the folder, upon the first iteration
