### ISSUE TITLE
`manimgl wordle.py InitialDemo` get  an error

### ISSUE THREAD

**Issue by War3cdota** [3b1b/videos#26]
**AttributeError: 'numpy.ndarray' object has no attribute 'get_coord'**

![image](https://user-images.githubusercontent.com/12780185/153180519-f4fbfb81-34be-4b30-a55e-7b47dffb65f7.png)
![image](https://user-images.githubusercontent.com/12780185/153181062-0c583d7b-3a59-4ba5-b983-9e05f99b0649.png)

Package | Version
-- | --
manimgl | v1.2.0 or latest
MiKTeX |  v22.1

**System information**
name|Version
-- | --
windows | 10
Python |  3.10.2

1. I have already installed [manimgl](https://github.com/3b1b/manim)
2. I got ` pattern_matrix.npy` by running `python wordle.py` 
3. When I ran `manimgl wordle.py InitialDemo`, I got the error, but I don't know where I was wrong

**Comment by ivanhrabcak** [comment]
I am experiencing the same issue (with windows 11, python 3.10, latest MikTeX, latest manimgl)

**Comment by KodySalak** [comment]
Same here - Gave up after this.

**Comment by johnsoe2** [comment]
You need to switch to the [video-work](https://github.com/3b1b/manim/tree/video-work) branch of the manim repo, which has not yet been merged into the master branch.

_c:\Users\XXX\manim>git checkout video-work
Switched to a new branch 'video-work'
Branch 'video-work' set up to track remote branch 'video-work' from 'origin'._

**Comment by 3b1b** [comment]
That branch has now been merged into manimgl's master. Hopefully, it works okay now?
