### ISSUE TITLE
Array size in wordle solver.

### ISSUE THREAD

**Issue by o-mcelhin** [3b1b/videos#27]
When attempting to run the wordle code, I get the following error:

ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.

I think this may be an internal setting, but it crashes at the line:

equality_grid = np.zeros((len(w1), len(w2), n, n), dtype=bool)

when trying to make a 12972 x 12972 array of zeros. Is there a way to overwrite this max size?

**Comment by Jonah-B-Kehillah** [comment]
Make sure that you are using a 64-bit version of python. I had the same error, but when I upgraded my version of python to a 64-bit one, the error went away.
