### ISSUE TITLE
[QUESTION/HELP] - Wordle Solver

### ISSUE THREAD

**Issue by therealOri** [3b1b/videos#29]
I can't for the life of me figure out how to run and use/play with the wordle solver..Nothing here is understandable nor do I know what to do, what goes where, what to install, what to edit, what file to run, what commands to execute, etc... 

The "wordle.py" file and it's related stuff is non existent now. Like it got deleted overnight. For idk what reason.. (Idk what file to run.)

A very simple step by step guide would be greatly appreciated for this difficult, confusing and mountainous mess of a repository. 

Any help on how to get the wordle solver to run, such as commands and where to run said commands is what I'm looking for.
(I'd ask this in a discussions area but that isn't enabled in this repo.)

God, the more I look at this repo, the code, and trying to figure out how anything works..the more confused and I get xD

**Comment by therealOri** [comment]
@3b1b 

Any advice or help?

**Comment by 3b1b** [comment]
Can you share more details on what happens if you go into the _2022/wordle/ folder and run "python simulations.py"?

To run the scenes from _2022/wordle/scenes.py, you'll have to have manim properly set up.

**Comment by therealOri** [comment]
@3b1b 
> Can you share more details on what happens if you go into the _2022/wordle/ folder and run "python simulations.py"?
> 
> To run the scenes from _2022/wordle/scenes.py, you'll have to have manim properly set up.

<br />
<br />

I get the following error:
```bash
Traceback (most recent call last):
  File "/home/ori/Desktop/videos/_2022/wordle/simulations.py", line 1, in <module>
    from manim_imports_ext import *
ModuleNotFoundError: No module named 'manim_imports_ext'
```

If I move `manim_imports_ext` and the `custom` folder (idk if it's needed) into the folder with `simulations.py` it'll start running and going through its games.

What do I do after it finishes? Like..what command(s) should I run and from where should they be ran?

**Comment by therealOri** [comment]
After `simulations.py` finishes, I get the following error:
```bash
Traceback (most recent call last):                                                                       
  File "/home/ori/Desktop/videos/_2022/wordle/simulations.py", line 805, in <module>
    results, decision_map = simulate_games(
  File "/home/ori/Desktop/videos/_2022/wordle/simulations.py", line 796, in simulate_games
    path = os.path.join(get_directories()["data"], "wordle", file)
KeyError: 'data'
```

**Comment by ItzMiracleOwO** [comment]
I tried adding the `manim_imports_ext` into the path
Now the command `python scenes.py` gives no output :/ @3b1b 

![image](https://user-images.githubusercontent.com/76854136/153522796-1aa132d3-d3be-47fa-8e05-3338a4fd7d94.png)

**Comment by ItzMiracleOwO** [comment]
Oh
![image](https://user-images.githubusercontent.com/76854136/153522838-03795d20-285b-4644-bfcf-5121404337d1.png)

**Comment by ItzMiracleOwO** [comment]
> Oh ![image](https://user-images.githubusercontent.com/76854136/153522838-03795d20-285b-4644-bfcf-5121404337d1.png)

But thats stuck tho

**Comment by ItzMiracleOwO** [comment]
> Oh ![image](https://user-images.githubusercontent.com/76854136/153522838-03795d20-285b-4644-bfcf-5121404337d1.png)

Forget about that. it just completed.
And `python scenes.py` still no output

**Comment by therealOri** [comment]
@3b1b 

I have found a way to get the .json files from running `python simulations.py`.

I do not know where those files should actually be as I just made the script output them in the "wordle" directory/folder. I don't know if they need to be moved somewhere else or kept there.

Also, I don't know what command(s) to run next or what to do in the python shell that is started after `simulations.py` finishes.
If you could let me know what to do next or if you have any more advice on how to actually run the wordle solver then It'd be very appreciated.

**Comment by therealOri** [comment]
Anyone know how to run wordle?

**Comment by ItzMiracleOwO** [comment]
It's still a mystery

**Comment by 3b1b** [comment]
You may want to look at https://github.com/3b1b/videos/issues/28

> Also, I don't know what command(s) to run next or what to do in the python shell that is started after simulations.py finishes.

The simulations.py file just contains a lot of helper functions to run the Worlde-solving algorithm, and when you run it as a script all it is meant to do is run a simulation of all the games for a given configuration, depending on what you put into the `if __name__ = "__main` section.

The scenes themselves, with interactive demos etc., are part of the scenes.py folder, and need to be run with manimgl. You can find details on installing manimgl in [its github page](https://github.com/3b1b/manim)

In general, the code posted to this repo is rather scrappy. I put it here because people are curious to see what's behind the videos, but it may not always be the most friendly to actively work with.
