### ISSUE TITLE
Where do you run the Wordle code?

### ISSUE THREAD

**Issue by SuperSuperHunter** [3b1b/videos#31]
I was wondering where you write the wordle code? is it in python? if so, how do you do it? I've never run manim before or any github code at that, can someone give me a full walkthrough on how to do it 

thanks in advance

**Comment by dalton77-get** [comment]
Do you mean where to find it? The wordle code is under the "_2022" directory and it is written on `python` 3.

**Comment by crypdick** [comment]
@dalton77-get I have copied the contents of `wordle/` to the root of this repo so that it can find the  `manim_imports_ext` module. I also ran `pip install manimlib`. Now I'm getting the following stacktrace:

```
Traceback (most recent call last):
  File "simulations.py", line 1, in <module>
    from manim_imports_ext import *
  File "/home/richard/src/3b1b/manim_imports_ext.py", line 3, in <module>
    from custom.backdrops import *
  File "/home/richard/src/3b1b/custom/backdrops.py", line 10, in <module>
    from manimlib.mobject.svg.tex_mobject import TexText
ImportError: cannot import name 'TexText' from 'manimlib.mobject.svg.tex_mobject' (/home/richard/miniconda/envs/wordle/lib/python3.8/site-packages/manimlib/mobject/svg/tex_mobject.py)
```

**Comment by dalton77-get** [comment]
Instead of running `pip install manimlib`, run `pip install manimgl`. See if that works.

**Comment by dalton77-get** [comment]
Oh, yes. That would definitely work.
