### ISSUE TITLE
Running `scenes.py InitialDemo` can't find manimlib

### ISSUE THREAD

**Issue by NoelleTGS** [3b1b/videos#32]
I'm trying to run the Wordle solver, and when I run `scenes.py InitialDemo` I always get an error about not being able to find manimlib. From what I know I have everything I need, so I have no idea why it isn't finding it.

```
Traceback (most recent call last):
  File "C:\Users\Noelle\Desktop\Wordle solver\scenes.py", line 1, in <module>
    from manim_imports_ext import *
  File "C:\Users\Noelle\Desktop\Wordle solver\manim_imports_ext.py", line 1, in <module>
    from manimlib import *
ModuleNotFoundError: No module named 'manimlib'
```

**Comment by NoelleTGS** [comment]
I didn't edit the file at all, seems it's coming from manim_imports_ext.py, so should I edit that file to replace manimlib with manimgl?

**Comment by dalton77-get** [comment]
Try running "pip install manimgl" in your terminal.

**Comment by 3b1b** [comment]
Are you able to run the example scenes from manimgl (see [here](https://3b1b.github.io/manim/getting_started/example_scenes.html))?

**Comment by NoelleTGS** [comment]
My bad, I was running the script incorrectly in the first place. I'm having the same issue as [here](https://github.com/3b1b/videos/issues/28#issuecomment-1034176445) now, and for whatever reason the solution [ferazambuja](https://github.com/3b1b/videos/issues/28#issuecomment-1035602348) gave just gives me an invalid syntax.
```
File "C:\Users\Noelle\Desktop\Wordle solver\scenes.py", line 1
    import sys sys.path.append(".") sys.path.append("..")
               ^^^
SyntaxError: invalid syntax
```

**Comment by NoelleTGS** [comment]
I'm a moron lol, that problem was literally solved further down in the thread.

**Comment by blackne0n** [comment]
Please comment with link to solution, thank you.

Alberto Giardino
________________________________
