### ISSUE TITLE
Issue with installing manimgl

### ISSUE THREAD

**Issue by JonnyAfouluadoulu** [3b1b/videos#33]
Whenever I try to install manim it comes up with this error, can anyone help?
![Screenshot (79)](https://user-images.githubusercontent.com/99401058/153585900-4d912936-932d-43cf-836a-2817c540dc1e.png)

**Comment by TonyCrane** [comment]
Where is the error?
And what are you doing?

**Comment by JonnyAfouluadoulu** [comment]
![Screenshot (82)](https://user-images.githubusercontent.com/99401058/153592489-05532e5c-f4f8-40b1-a5f3-5c10a3ffd212.png)

**Comment by TonyCrane** [comment]
Please master python before going to use manim.
You should run the command in the terminal, not to run them as python script...

**Comment by dalton77-get** [comment]
In your screenshots, you are running the "pip install manimgl" and "manimgl" commands in a python script, which is why it doesn't recognize what you are doing. However, if you open the command prompt/powershell and run those commands, you should have a better result.
