### ISSUE TITLE
Problem with scenes.py

### ISSUE THREAD

**Issue by sethyo7** [3b1b/videos#34]
I got simulations.py to work but when I run scenes.py nothing happens. There are no errors it just creates a new line and does nothing. I have all the manimgl requirements and have it installed.

**Comment by dalton77-get** [comment]
Did you run "manimgl scenes.py" as opposed to "python3 scenes.py" or "python scenes.py"?

**Comment by sethyo7** [comment]
I just did python -m manimlib scenes.py because that is how i got example scenes to work and now its saying there is no module called manim_imports_ext even though it is in my manim folder. What is also weird is that a ran into thee same problem when trying to run simulations.py but i fixed by putting manim_imports_ext into the same place as simuations.py and the custom folder.

**Comment by sethyo7** [comment]
I got it to work by making the directory the file my scenes.py is in, but now I can only run scene 74  and 76 without getting errors.

**Comment by sethyo7** [comment]
I got some more scenes too work but I still have float division by zero error on a bunch of scenes
