### ISSUE TITLE
checkpoint_paste() is not defined?

### ISSUE THREAD

**Issue by HyperPos** [3b1b/videos#78]
After running "manimgl" to get an interactive ipython terminal I tried to write: "checkpoint_paste()".
Something went wrong :)

![image](https://github.com/user-attachments/assets/9b9a0be0-be75-4e16-8134-b8c86e1a3ccc)

**Comment by VladimirFokow** [comment]
Same error. I also see an error `IPython/terminal/embed.py:304: UserWarning: Failed to get module start_inserted_embed`, maybe it's related?

```bash
$ manimgl start.py SquareToCircle -se 11
ManimGL v1.6.1
[21:20:31] INFO     Using the default configuration file, which you can modify in                                                                                        
                                                                                                                                                                                             `/path/to/lib/python3.11/site-packages/manimlib/default_config.yml`                                               
           INFO     If you want to create a local configuration file, you can create a file named `custom_config.yml`, or run `manimgl --config`
           INFO     Tips: Now the embed iPython terminal is open. But you can't interact with the window directly. To do so, you need to type `touch()` or                
                                                                                                                                                                                      
        `self.interact()`                                                                                                                                                 
Python 3.11.6 (main, Oct  9 2023, 06:16:45) [Clang 15.0.0 (clang-1500.0.40.1)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.28.0 -- An enhanced Interactive Python. Type '?' for help.
/path/to/lib/python3.11/site-packages/IPython/terminal/embed.py:304: UserWarning: Failed to get module start_inserted_embed
  warnings.warn("Failed to get module %s" % \
```

**Comment by Splines** [comment]
Did you use the latest version of manim that is available on pip? I don't think it has this command available. Instead, use the latest commit on the `master` branch. Clone the repo, then do `pip install -e .` inside it, see [here](https://github.com/3b1b/manim?tab=readme-ov-file#directly). At least, that worked for me.

**Comment by HyperPos** [comment]
@Splines Thanks for the reply! Yeah. I'm using the “online-pip” version, so I'll give it a shot :)

**Comment by HyperPos** [comment]
@Splines Yep! It worked :) Thanks again!
---
If someone is interested in other issues for example:

**> manimgl error: subprocess-exited-with-error manim**
When running `pip install -e .`

**> TypeError: 'staticmethod' object is not callable**
When running `manimgl`. 

----
Solution: Change Python version. Python 3.10.0 worked for me.
