### ISSUE TITLE
Clarify usage intention / conditions: (maybe) publish "videos"-repository under an official CC-license

### ISSUE THREAD

**Issue by MarkusTiede** [3b1b/videos#79]
Hi @3b1b - first of all: thank you! I really enjoy watching and recommending your videos, I just recently stumbled across your video "How I animate 3Blue1Brown" where you also mention (and link) that all of the source code your videos is publicly available: awesome!  

However I read this in the readme:

https://github.com/3b1b/videos/blob/bfa09d02afa9b802004525a86592162021afede9/README.md?plain=1#L8

and now I'm a bit confused whether I'm allowed to use the source code or not. Could you maybe put this repository under an official [CC-License](https://creativecommons.org/share-your-work/cclicenses/) to grant the public permission to use your creative work which is otherwise under exclusive copyright law?

If needed I'd be glad to assist here if you like.

**Comment by 3b1b** [comment]
Hi Markus,

I'd like it all to be publically visible, but without necessarily giving universal permission to _reuse_ video content.

My intent with this repository is to show the code behind the videos, as a catch-all answer to the question of "how was that animation made" for any given video. At the same time, I intend to maintain the copyright for videos, and the assets that went into them. I'm happy for people to use this repo to get inspiration or to start with manim, but directly using the content in their work would still require explicit permission.

If you have suggestions for more explicit phrasing/licensing in the Readme or elsewhere, let me know.

Grant

**Comment by MarkusTiede** [comment]
Hi @3b1b,

thanks for your instant response - really appreciate that: I understand your intentions.

This clear usage information would (imho) also be quite useful for all the users / forks (1k+) of this repository; from what I understand so far [the "non-commercial" and "share-alike" (aka copyleft) flavour of CC licenses](https://creativecommons.org/licenses/by-nc-sa/4.0/) might be fitting here:
 - ND: without further permission (and by putting this repository under a CC license you do not loose the copyright at all) nobody is allowed to use this for [commercial purposes](https://creativecommons.org/faq/#does-my-use-violate-the-noncommercial-clause-of-the-licenses)
 - SA: all users, beside giving attribution to you and your work, have to license their work als well under the same CC license : hence you'e be able to benefit (and enforce that) from the "inspiration" and ideas they have. 

You could also state that only certain files / parts of the repository are published under these license terms.

IMHO form an intellectual property point of view - without an explicit license - [nobody is really (actually, legally) able to use, only "view and fork", your code without at the same time also violating some of your rights (to some extent)](https://opensource.guide/legal/#are-public-github-projects-open-source) as the [GitHub Terms of Service - D5. License Grant to Other Users](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#5-license-grant-to-other-users) applies.

If intended it might be useful adding an explicit link to the GitHub Terms of Service D5 section within you readme.

Thanks for discussing / considering my thoughts on this!

Markus

**Comment by 3b1b** [comment]
CC BY-NC-SA seems reasonable in this case. If you had any interest in adding that license as a PR, and/or to include any clarification you think is warranted in the Readme, I'd happily look it over and merge.

**Comment by MarkusTiede** [comment]
Sure - thanks; further aspects may be discussed at the corresponding PR: https://github.com/3b1b/videos/pull/80

**Comment by VladimirFokow** [comment]
Hello!
Thanks for the awesome work!

If, for example, I'm adapting a *workflow* (e.g. [this one](https://github.com/3b1b/videos/blob/4203c7a9a54842b98c943d7d8f5d85dea330c543/sublime_custom_commands/manim_plugins.py#L125-L149)) for another editor & language (e.g. [this one](https://github.com/VladimirFokow/vscode-manim/blob/bebbd4bc4b0bc27af902425572bc1871a62959c3/src/extension.ts#L33-L122)) –
is it required still to be under CC BY-NC-SA?

Both the language and editor are different (TypeScript & VSCode), yet the workflow steps are adapted.

Thanks!

**Comment by 3b1b** [comment]
Great question, to me, it feels like the workflow is mostly a matter of putting keyboard shortcuts to existing manim commands, so you should be free to do whatever you want there.

I wonder if the workflow would be better placed inside the manim repo itself.
