### ISSUE TITLE
Editing one graph edits all

### ISSUE THREAD

**Issue by Rosuav** [3b1b/videos#8]
Not sure if this is the best place to mention this. The interactive Fourier transform page has an oddity: if you edit the frequency selection in one interactive graph, all of them change the red lines. The white dot that tracks the mouse still uses the specific graph's frequency set, but it's running across an incorrect red line that belongs on a different graph.

**Comment by 3b1b** [comment]
Thanks for letting me know, feel free to raise the issue (or to make a pull request) on [this repo](https://github.com/3b1b/3Blue1Brown.com/)
