### ISSUE TITLE
could you make more lesson about that 2d to 3d and 2d to 3d through camera

### ISSUE THREAD

**Issue by biyaa** [3b1b/videos#9]
Thank you for all intuition and beautiful lessons,  but some others , such as  2d to 3d and 2d to 3d through camera, intrsic matrix, extern matrix,  how to know 2d plane project camera   etc, I don't understand.
could you make lessons more about it.

thank you

**Comment by Zeyecx** [comment]
Hi @biyaa , 
Can you start the different projects or do you also have different problems? I and several others also have problems compiling the various files with manim. How did you get it to find the imports?

With kind regards. 
@Zeyecx

**Comment by 3b1b** [comment]
The place I turn to in looking for video requests is the top thread on [this subreddit](https://www.reddit.com/r/3blue1brown)
